-- 0008_reorder_tracking.sql
-- Automatic restock/reorder tracking. One trigger on inventory is the single
-- source of truth for Expo + web: every stock change (sale, void, stock-in,
-- offline replay, direct admin write) funnels through it.

-- ---------------------------------------------------------------------------
-- 1) Target stock level per inventory row. NULL = feature inactive for it.
-- ---------------------------------------------------------------------------
alter table inventory
  add column if not exists par_level integer check (par_level is null or par_level >= 0);

-- ---------------------------------------------------------------------------
-- 2) Restock requests.
-- ---------------------------------------------------------------------------
create table if not exists reorder_requests (
  request_id             bigint generated by default as identity primary key,
  product_id             bigint not null references product (product_id) on delete cascade,
  current_stock_snapshot integer not null,
  reorder_point_snapshot integer not null,
  par_level_snapshot     integer not null,
  suggested_quantity     integer not null check (suggested_quantity >= 0),
  status                 text not null default 'pending'
    check (status in ('pending', 'ordered', 'received', 'cancelled')),
  supplier               text,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  resolved_at            timestamptz,
  resolved_by            uuid references "user" (user_id)
);

-- ---------------------------------------------------------------------------
-- 3) At most one open ('pending' | 'ordered') request per product.
-- ---------------------------------------------------------------------------
create unique index if not exists uq_reorder_open_per_product
  on reorder_requests (product_id)
  where status in ('pending', 'ordered');

-- ---------------------------------------------------------------------------
-- 4) Trigger: create-or-refresh the open request on every quantity change.
--    SECURITY DEFINER (0003 style) so cashier-path RPC writes can never fail
--    on the reorder insert; RLS still gates all direct table access.
-- ---------------------------------------------------------------------------
create or replace function public.check_reorder_level()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_open_id  bigint;
  v_supplier text;
begin
  if NEW.par_level is null then
    return NEW;
  end if;
  if NEW.quantity <= NEW.reorder_level then
    select request_id into v_open_id
      from reorder_requests
      where product_id = NEW.product_id and status in ('pending', 'ordered')
      for update;
    if v_open_id is not null then
      update reorder_requests
        set current_stock_snapshot = NEW.quantity,
            reorder_point_snapshot = NEW.reorder_level,
            par_level_snapshot = NEW.par_level,
            suggested_quantity = greatest(NEW.par_level - NEW.quantity, 0),
            updated_at = now()
        where request_id = v_open_id;
    else
      select supplier into v_supplier
        from stock_movements
        where stock_id = NEW.stock_id and supplier is not null
        order by date desc
        limit 1;
      insert into reorder_requests
        (product_id, current_stock_snapshot, reorder_point_snapshot,
         par_level_snapshot, suggested_quantity, status, supplier)
        values
        (NEW.product_id, NEW.quantity, NEW.reorder_level,
         NEW.par_level, greatest(NEW.par_level - NEW.quantity, 0),
         'pending', v_supplier);
    end if;
  else
    -- Recovered above the threshold: refresh snapshots, never auto-close.
    -- Closing (received/cancelled) is always a human decision.
    update reorder_requests
      set current_stock_snapshot = NEW.quantity,
          reorder_point_snapshot = NEW.reorder_level,
          par_level_snapshot = NEW.par_level,
          suggested_quantity = greatest(NEW.par_level - NEW.quantity, 0),
          updated_at = now()
      where product_id = NEW.product_id and status in ('pending', 'ordered');
  end if;
  return NEW;
end;
$$;

drop trigger if exists trg_check_reorder_level on inventory;
create trigger trg_check_reorder_level
  after update of quantity on inventory
  for each row execute function public.check_reorder_level();

revoke all on function public.check_reorder_level() from public;
-- No grant: only the trigger invokes it.

-- ---------------------------------------------------------------------------
-- 5) Auto-touch updated_at on app-side edits.
-- ---------------------------------------------------------------------------
create or replace function public.touch_reorder_updated_at()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  NEW.updated_at = now();
  return NEW;
end;
$$;

drop trigger if exists trg_touch_reorder_updated_at on reorder_requests;
create trigger trg_touch_reorder_updated_at
  before update on reorder_requests
  for each row execute function public.touch_reorder_updated_at();

revoke all on function public.touch_reorder_updated_at() from public;

-- ---------------------------------------------------------------------------
-- 6) RLS: admin only (0003 style — policies only, no table grants).
--    Cashiers get no policies → all access denied.
-- ---------------------------------------------------------------------------
alter table reorder_requests enable row level security;
drop policy if exists "reorder_admin_all" on reorder_requests;
create policy "reorder_admin_all" on reorder_requests
  for all using (get_app_role() = 'admin') with check (get_app_role() = 'admin');
