-- 0010_daily_quota_ingredient_inventory.sql
-- Replace finished-product stock with ingredient inventory + daily quotas.
-- Legacy inventory/restock tables remain intact for historical records only.

alter table product add column if not exists default_daily_quota integer not null default 30;

do $$ begin
  alter table product add constraint product_default_daily_quota_nonnegative
    check (default_daily_quota >= 0);
exception when duplicate_object then null;
end $$;

create or replace function public.business_date(p_at timestamptz default now())
returns date language sql stable set search_path = public
as $$ select (p_at at time zone 'Asia/Manila')::date $$;

create table if not exists ingredient (
  ingredient_id bigint generated by default as identity primary key,
  name text not null unique,
  unit text not null check (unit in ('g', 'kg', 'ml', 'l', 'pcs', 'serving')),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists ingredient_inventory (
  ingredient_id bigint primary key references ingredient(ingredient_id) on delete restrict,
  quantity numeric(14,3) not null default 0 check (quantity >= 0),
  reorder_level numeric(14,3) not null default 0 check (reorder_level >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists product_recipe (
  product_id bigint not null references product(product_id) on delete cascade,
  ingredient_id bigint not null references ingredient(ingredient_id) on delete restrict,
  quantity numeric(14,3) not null check (quantity > 0),
  primary key (product_id, ingredient_id)
);

create table if not exists daily_product_quotas (
  product_id bigint not null references product(product_id) on delete cascade,
  business_date date not null,
  initial_quota integer not null check (initial_quota >= 0),
  daily_quota integer not null check (daily_quota >= 0),
  created_by uuid references "user"(user_id),
  updated_by uuid references "user"(user_id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (product_id, business_date)
);

create table if not exists quota_changes (
  quota_change_id bigint generated by default as identity primary key,
  product_id bigint not null references product(product_id) on delete restrict,
  business_date date not null,
  previous_quota integer not null,
  new_quota integer not null,
  changed_by uuid not null references "user"(user_id),
  changed_by_role text not null check (changed_by_role in ('admin', 'cashier')),
  reason text,
  changed_at timestamptz not null default now()
);

create table if not exists audit_log (
  audit_id uuid primary key default gen_random_uuid(),
  event_type text not null,
  entity_type text not null,
  entity_id text,
  actor_id uuid references "user"(user_id),
  actor_role text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists stock_in_receipts (
  stock_in_id uuid primary key default gen_random_uuid(),
  reference_number text,
  supplier text,
  received_at timestamptz not null,
  recorded_by uuid not null references "user"(user_id),
  notes text,
  payment_method text check (payment_method in ('cash', 'gcash', 'maya', 'bank', 'other')),
  ewallet_reference text,
  evidence_path text,
  created_at timestamptz not null default now()
);

create table if not exists stock_in_items (
  stock_in_item_id bigint generated by default as identity primary key,
  stock_in_id uuid not null references stock_in_receipts(stock_in_id) on delete cascade,
  ingredient_id bigint not null references ingredient(ingredient_id) on delete restrict,
  quantity numeric(14,3) not null check (quantity > 0),
  unit text not null
);

create table if not exists ingredient_movements (
  movement_id bigint generated by default as identity primary key,
  ingredient_id bigint not null references ingredient(ingredient_id) on delete restrict,
  movement_type text not null check (movement_type in ('stock_in', 'sale', 'void', 'adjustment')),
  quantity numeric(14,3) not null check (quantity > 0),
  transaction_id uuid references transactions(id) on delete restrict,
  stock_in_id uuid references stock_in_receipts(stock_in_id) on delete restrict,
  actor_id uuid references "user"(user_id),
  note text,
  occurred_at timestamptz not null default now()
);

alter table transactions add column if not exists voided_by uuid references "user"(user_id);
alter table transactions add column if not exists voided_at timestamptz;

create table if not exists cashier_shifts (
  shift_id uuid primary key default gen_random_uuid(),
  user_id uuid not null references "user"(user_id),
  business_date date not null,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  starting_cash numeric(12,2) not null check (starting_cash >= 0),
  status text not null default 'open' check (status in ('open', 'closed')),
  notes text
);

create unique index if not exists cashier_one_open_shift
  on cashier_shifts(user_id) where status = 'open';

create table if not exists cash_turnovers (
  turnover_id uuid primary key default gen_random_uuid(),
  shift_id uuid not null unique references cashier_shifts(shift_id) on delete restrict,
  submitted_by uuid not null references "user"(user_id),
  submitted_at timestamptz not null default now(),
  starting_cash numeric(12,2) not null,
  cash_sales numeric(12,2) not null,
  expected_cash numeric(12,2) not null,
  counted_cash numeric(12,2) not null,
  variance numeric(12,2) not null,
  status text not null default 'pending' check (status in ('pending', 'verified', 'flagged')),
  notes text,
  verified_by uuid references "user"(user_id),
  verified_at timestamptz,
  verification_note text
);

create index if not exists quota_changes_product_day_idx
  on quota_changes(product_id, business_date, changed_at desc);
create index if not exists ingredient_movements_ingredient_idx
  on ingredient_movements(ingredient_id, occurred_at desc);
create index if not exists cashier_shifts_user_date_idx
  on cashier_shifts(user_id, business_date desc);

alter table ingredient enable row level security;
alter table ingredient_inventory enable row level security;
alter table product_recipe enable row level security;
alter table daily_product_quotas enable row level security;
alter table quota_changes enable row level security;
alter table audit_log enable row level security;
alter table stock_in_receipts enable row level security;
alter table stock_in_items enable row level security;
alter table ingredient_movements enable row level security;
alter table cashier_shifts enable row level security;
alter table cash_turnovers enable row level security;

create policy "ingredient_staff_read" on ingredient for select
  using (get_app_role() in ('admin', 'cashier'));
create policy "ingredient_admin_write" on ingredient for all
  using (get_app_role() = 'admin') with check (get_app_role() = 'admin');
create policy "ingredient_inventory_staff_read" on ingredient_inventory for select
  using (get_app_role() in ('admin', 'cashier'));
create policy "ingredient_inventory_admin_write" on ingredient_inventory for all
  using (get_app_role() = 'admin') with check (get_app_role() = 'admin');
create policy "recipe_staff_read" on product_recipe for select
  using (get_app_role() in ('admin', 'cashier'));
create policy "recipe_admin_write" on product_recipe for all
  using (get_app_role() = 'admin') with check (get_app_role() = 'admin');
create policy "daily_quota_staff_read" on daily_product_quotas for select
  using (get_app_role() in ('admin', 'cashier'));
create policy "quota_changes_admin_read" on quota_changes for select
  using (get_app_role() = 'admin');
create policy "audit_admin_read" on audit_log for select
  using (get_app_role() = 'admin');
create policy "stock_receipts_admin_read" on stock_in_receipts for select
  using (get_app_role() = 'admin');
create policy "stock_items_admin_read" on stock_in_items for select
  using (get_app_role() = 'admin');
create policy "ingredient_movements_admin_read" on ingredient_movements for select
  using (get_app_role() = 'admin');
create policy "shift_admin_read" on cashier_shifts for select
  using (get_app_role() = 'admin');
create policy "shift_own_read" on cashier_shifts for select
  using (user_id = auth.uid());
create policy "turnover_admin_read" on cash_turnovers for select
  using (get_app_role() = 'admin');
create policy "turnover_own_read" on cash_turnovers for select
  using (submitted_by = auth.uid());

-- Finished-product stock-in is obsolete. Preserve its tables and records but
-- remove the executable mutation path from application users.
revoke execute on function public.adjust_stock(bigint, integer, text) from authenticated;

create or replace function public.ensure_daily_product_quotas(
  p_business_date date default public.business_date()
)
returns void language plpgsql security definer set search_path = public as $$
declare
  v_role text := get_app_role();
begin
  if v_role not in ('admin', 'cashier') then raise exception 'Not authorized'; end if;

  with inserted as (
    insert into daily_product_quotas
      (product_id, business_date, initial_quota, daily_quota, created_by, updated_by)
    select product_id, p_business_date, default_daily_quota, default_daily_quota,
           auth.uid(), auth.uid()
    from product where is_available
    on conflict (product_id, business_date) do nothing
    returning product_id, daily_quota
  )
  insert into audit_log(event_type, entity_type, entity_id, actor_id, actor_role, details)
  select 'daily_quota_created', 'product', product_id::text, auth.uid(), v_role,
         jsonb_build_object('business_date', p_business_date, 'quota', daily_quota)
  from inserted;
end;
$$;

revoke all on function public.ensure_daily_product_quotas(date) from public;
grant execute on function public.ensure_daily_product_quotas(date) to authenticated;

create or replace function public.get_today_product_quotas()
returns table (
  product_id bigint,
  product_name text,
  default_quota integer,
  daily_quota integer,
  sold_quantity integer,
  remaining_quantity integer
)
language plpgsql security definer set search_path = public as $$
declare v_day date := business_date();
begin
  if get_app_role() not in ('admin', 'cashier') then raise exception 'Not authorized'; end if;
  perform ensure_daily_product_quotas(v_day);
  return query
    select p.product_id, p.name, p.default_daily_quota, q.daily_quota,
      coalesce(s.sold, 0)::integer,
      greatest(q.daily_quota - coalesce(s.sold, 0), 0)::integer
    from product p
    join daily_product_quotas q on q.product_id = p.product_id and q.business_date = v_day
    left join (
      select ti.product_id, sum(ti.quantity)::integer sold
      from transaction_items ti join transactions t on t.id = ti.transaction_id
      where t.status = 'completed' and business_date(t.date) = v_day
      group by ti.product_id
    ) s on s.product_id = p.product_id
    where p.is_available
    order by p.name;
end;
$$;

revoke all on function public.get_today_product_quotas() from public;
grant execute on function public.get_today_product_quotas() to authenticated;

create or replace function public.set_today_product_quota(
  p_product_id bigint,
  p_new_quota integer,
  p_reason text default null
)
returns void language plpgsql security definer set search_path = public as $$
declare
  v_role text := get_app_role();
  v_day date := business_date();
  v_old integer;
  v_sold integer;
begin
  if v_role not in ('admin', 'cashier') then raise exception 'Not authorized'; end if;
  if p_new_quota < 0 then raise exception 'Daily quota cannot be negative'; end if;
  perform ensure_daily_product_quotas(v_day);
  select daily_quota into v_old from daily_product_quotas
    where product_id = p_product_id and business_date = v_day for update;
  if v_old is null then raise exception 'Product quota not found'; end if;
  select coalesce(sum(ti.quantity), 0)::integer into v_sold
    from transaction_items ti join transactions t on t.id = ti.transaction_id
    where ti.product_id = p_product_id and t.status = 'completed'
      and business_date(t.date) = v_day;
  if p_new_quota < v_sold then
    raise exception 'Daily quota cannot be lower than the quantity already sold. Minimum valid quota: %', v_sold;
  end if;
  if p_new_quota = v_old then return; end if;
  update daily_product_quotas set daily_quota = p_new_quota,
    updated_by = auth.uid(), updated_at = now()
    where product_id = p_product_id and business_date = v_day;
  insert into quota_changes(product_id, business_date, previous_quota, new_quota,
    changed_by, changed_by_role, reason)
  values (p_product_id, v_day, v_old, p_new_quota, auth.uid(), v_role, nullif(trim(p_reason), ''));
  insert into audit_log(event_type, entity_type, entity_id, actor_id, actor_role, details)
  values (case when p_new_quota > v_old then 'quota_increased' else 'quota_decreased' end,
    'daily_product_quota', p_product_id::text, auth.uid(), v_role,
    jsonb_build_object('business_date', v_day, 'old_quota', v_old,
      'new_quota', p_new_quota, 'reason', nullif(trim(p_reason), '')));
end;
$$;

revoke all on function public.set_today_product_quota(bigint, integer, text) from public;
grant execute on function public.set_today_product_quota(bigint, integer, text) to authenticated;

create or replace function public.set_default_product_quota(
  p_product_id bigint,
  p_new_quota integer,
  p_reason text default null
)
returns void language plpgsql security definer set search_path = public as $$
declare v_old integer;
begin
  if get_app_role() <> 'admin' then raise exception 'Admin only'; end if;
  if p_new_quota < 0 then raise exception 'Default quota cannot be negative'; end if;
  select default_daily_quota into v_old from product where product_id = p_product_id for update;
  if v_old is null then raise exception 'Product not found'; end if;
  update product set default_daily_quota = p_new_quota where product_id = p_product_id;
  insert into audit_log(event_type, entity_type, entity_id, actor_id, actor_role, details)
  values ('default_quota_changed', 'product', p_product_id::text, auth.uid(), 'admin',
    jsonb_build_object('old_quota', v_old, 'new_quota', p_new_quota,
      'reason', nullif(trim(p_reason), '')));
end;
$$;

revoke all on function public.set_default_product_quota(bigint, integer, text) from public;
grant execute on function public.set_default_product_quota(bigint, integer, text) to authenticated;

create or replace function public.record_ingredient_stock_in(
  p_reference_number text,
  p_supplier text,
  p_received_at timestamptz,
  p_notes text,
  p_payment_method text,
  p_ewallet_reference text,
  p_evidence_path text,
  p_items jsonb
)
returns uuid language plpgsql security definer set search_path = public as $$
declare
  v_id uuid := gen_random_uuid();
  v_item jsonb;
  v_ingredient_id bigint;
  v_quantity numeric;
  v_unit text;
begin
  if get_app_role() <> 'admin' then raise exception 'Admin only'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'At least one ingredient is required';
  end if;
  insert into stock_in_receipts(stock_in_id, reference_number, supplier, received_at,
    recorded_by, notes, payment_method, ewallet_reference, evidence_path)
  values (v_id, nullif(trim(p_reference_number), ''), nullif(trim(p_supplier), ''),
    p_received_at, auth.uid(), nullif(trim(p_notes), ''), nullif(trim(p_payment_method), ''),
    nullif(trim(p_ewallet_reference), ''), nullif(trim(p_evidence_path), ''));
  for v_item in select value from jsonb_array_elements(p_items) loop
    v_ingredient_id := (v_item->>'ingredient_id')::bigint;
    v_quantity := (v_item->>'quantity')::numeric;
    if v_quantity <= 0 then raise exception 'Stock-in quantity must be greater than zero'; end if;
    select unit into v_unit from ingredient where ingredient_id = v_ingredient_id and is_active;
    if v_unit is null then raise exception 'Ingredient not found'; end if;
    insert into stock_in_items(stock_in_id, ingredient_id, quantity, unit)
      values (v_id, v_ingredient_id, v_quantity, v_unit);
    insert into ingredient_inventory(ingredient_id, quantity, reorder_level)
      values (v_ingredient_id, v_quantity, 0)
      on conflict (ingredient_id) do update set
        quantity = ingredient_inventory.quantity + excluded.quantity, updated_at = now();
    insert into ingredient_movements(ingredient_id, movement_type, quantity, stock_in_id, actor_id)
      values (v_ingredient_id, 'stock_in', v_quantity, v_id, auth.uid());
  end loop;
  insert into audit_log(event_type, entity_type, entity_id, actor_id, actor_role, details)
    values ('stock_in_created', 'stock_in_receipt', v_id::text, auth.uid(), 'admin',
      jsonb_build_object('reference_number', nullif(trim(p_reference_number), ''),
        'item_count', jsonb_array_length(p_items), 'has_evidence', p_evidence_path is not null));
  return v_id;
end;
$$;

revoke all on function public.record_ingredient_stock_in(text, text, timestamptz, text, text, text, text, jsonb) from public;
grant execute on function public.record_ingredient_stock_in(text, text, timestamptz, text, text, text, text, jsonb) to authenticated;

create or replace function public.open_cashier_shift(p_starting_cash numeric, p_notes text default null)
returns uuid language plpgsql security definer set search_path = public as $$
declare v_id uuid := gen_random_uuid(); v_role text := get_app_role();
begin
  if v_role <> 'cashier' then raise exception 'Cashier only'; end if;
  if p_starting_cash < 0 then raise exception 'Starting cash cannot be negative'; end if;
  insert into cashier_shifts(shift_id, user_id, business_date, starting_cash, notes)
    values (v_id, auth.uid(), business_date(), p_starting_cash, nullif(trim(p_notes), ''));
  insert into audit_log(event_type, entity_type, entity_id, actor_id, actor_role, details)
    values ('shift_opened', 'cashier_shift', v_id::text, auth.uid(), v_role,
      jsonb_build_object('starting_cash', p_starting_cash));
  return v_id;
exception when unique_violation then raise exception 'An open shift already exists';
end;
$$;

revoke all on function public.open_cashier_shift(numeric, text) from public;
grant execute on function public.open_cashier_shift(numeric, text) to authenticated;

create or replace function public.submit_cash_turnover(
  p_shift_id uuid, p_counted_cash numeric, p_notes text default null
)
returns uuid language plpgsql security definer set search_path = public as $$
declare
  v_shift cashier_shifts%rowtype;
  v_cash_sales numeric := 0;
  v_expected numeric;
  v_id uuid := gen_random_uuid();
begin
  if get_app_role() <> 'cashier' then raise exception 'Cashier only'; end if;
  if p_counted_cash < 0 then raise exception 'Counted cash cannot be negative'; end if;
  select * into v_shift from cashier_shifts where shift_id = p_shift_id for update;
  if v_shift.user_id <> auth.uid() or v_shift.status <> 'open' then raise exception 'Open shift not found'; end if;
  select coalesce(sum(total_amount), 0) into v_cash_sales from transactions
    where user_id = auth.uid() and payment_mode = 'cash' and status = 'completed'
      and date >= v_shift.started_at and date <= now();
  v_expected := v_shift.starting_cash + v_cash_sales;
  insert into cash_turnovers(turnover_id, shift_id, submitted_by, starting_cash,
    cash_sales, expected_cash, counted_cash, variance, notes)
  values (v_id, p_shift_id, auth.uid(), v_shift.starting_cash, v_cash_sales,
    v_expected, p_counted_cash, p_counted_cash - v_expected, nullif(trim(p_notes), ''));
  update cashier_shifts set status = 'closed', ended_at = now() where shift_id = p_shift_id;
  insert into audit_log(event_type, entity_type, entity_id, actor_id, actor_role, details)
    values ('cash_turnover_submitted', 'cash_turnover', v_id::text, auth.uid(), 'cashier',
      jsonb_build_object('shift_id', p_shift_id, 'expected_cash', v_expected,
        'counted_cash', p_counted_cash, 'variance', p_counted_cash - v_expected));
  return v_id;
end;
$$;

revoke all on function public.submit_cash_turnover(uuid, numeric, text) from public;
grant execute on function public.submit_cash_turnover(uuid, numeric, text) to authenticated;

create or replace function public.verify_cash_turnover(
  p_turnover_id uuid, p_status text, p_note text default null
)
returns void language plpgsql security definer set search_path = public as $$
begin
  if get_app_role() <> 'admin' then raise exception 'Admin only'; end if;
  if p_status not in ('verified', 'flagged') then raise exception 'Invalid verification status'; end if;
  update cash_turnovers set status = p_status, verified_by = auth.uid(),
    verified_at = now(), verification_note = nullif(trim(p_note), '')
    where turnover_id = p_turnover_id;
  if not found then raise exception 'Cash turnover not found'; end if;
  insert into audit_log(event_type, entity_type, entity_id, actor_id, actor_role, details)
    values (case when p_status = 'verified' then 'cash_turnover_verified' else 'cash_turnover_flagged' end,
      'cash_turnover', p_turnover_id::text, auth.uid(), 'admin',
      jsonb_build_object('note', nullif(trim(p_note), '')));
end;
$$;

revoke all on function public.verify_cash_turnover(uuid, text, text) from public;
grant execute on function public.verify_cash_turnover(uuid, text, text) to authenticated;

-- Atomic sale: lock quota rows, reject overselling, and deduct exact recipe
-- requirements. Ingredient movements are retained for exact void reversal.
create or replace function public.process_sale(
  p_transaction_id uuid,
  p_payment_mode text,
  p_amount_received numeric,
  p_change_given numeric,
  p_items jsonb,
  p_date timestamptz
)
returns uuid language plpgsql security definer set search_path = public as $$
declare
  v_user_id uuid := auth.uid();
  v_role text := get_app_role();
  v_total numeric := 0;
  v_day date := business_date(p_date);
  v_order_no integer;
  v_item jsonb;
  v_product_id bigint;
  v_qty integer;
  v_price numeric;
  v_quota integer;
  v_sold integer;
  v_requirement record;
  v_on_hand numeric;
begin
  if v_role not in ('admin', 'cashier') then raise exception 'Not authenticated'; end if;
  if p_payment_mode not in ('cash', 'gcash', 'maya') then raise exception 'Unknown payment method'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then raise exception 'Cart is empty'; end if;
  if exists (select 1 from transactions where id = p_transaction_id) then return p_transaction_id; end if;
  perform ensure_daily_product_quotas(v_day);
  insert into order_number_counter(day, last) values (v_day, 0) on conflict (day) do nothing;
  update order_number_counter set last = last + 1 where day = v_day returning last into v_order_no;
  insert into transactions(id, user_id, total_amount, payment_mode, date, status,
    amount_received, change_given, order_number)
  values (p_transaction_id, v_user_id, 0, p_payment_mode, p_date, 'completed',
    p_amount_received, p_change_given, v_order_no);

  for v_item in select value from jsonb_array_elements(p_items) loop
    v_product_id := (v_item->>'product_id')::bigint;
    v_qty := (v_item->>'quantity')::integer;
    if v_qty <= 0 then raise exception 'Quantity must be greater than zero'; end if;
    select price into v_price from product where product_id = v_product_id and is_available;
    if v_price is null then raise exception 'Product % not found or unavailable', v_product_id; end if;
    select daily_quota into v_quota from daily_product_quotas
      where product_id = v_product_id and business_date = v_day for update;
    select coalesce(sum(ti.quantity), 0)::integer into v_sold
      from transaction_items ti join transactions t on t.id = ti.transaction_id
      where ti.product_id = v_product_id and t.status = 'completed' and business_date(t.date) = v_day;
    if v_sold + v_qty > v_quota then raise exception 'Daily quota reached for product %', v_product_id; end if;
    insert into transaction_items(id, transaction_id, product_id, quantity, subtotal)
      values (gen_random_uuid(), p_transaction_id, v_product_id, v_qty, v_price * v_qty);
    v_total := v_total + v_price * v_qty;
  end loop;

  for v_requirement in
    select pr.ingredient_id, sum(pr.quantity * (item->>'quantity')::integer) as required
    from jsonb_array_elements(p_items) item
    join product_recipe pr on pr.product_id = (item->>'product_id')::bigint
    group by pr.ingredient_id order by pr.ingredient_id
  loop
    select quantity into v_on_hand from ingredient_inventory
      where ingredient_id = v_requirement.ingredient_id for update;
    if v_on_hand is null or v_on_hand < v_requirement.required then
      raise exception 'Insufficient ingredient stock for ingredient %', v_requirement.ingredient_id;
    end if;
    update ingredient_inventory set quantity = quantity - v_requirement.required,
      updated_at = now() where ingredient_id = v_requirement.ingredient_id;
    insert into ingredient_movements(ingredient_id, movement_type, quantity,
      transaction_id, actor_id, occurred_at)
    values (v_requirement.ingredient_id, 'sale', v_requirement.required,
      p_transaction_id, v_user_id, p_date);
  end loop;
  update transactions set total_amount = v_total where id = p_transaction_id;
  insert into audit_log(event_type, entity_type, entity_id, actor_id, actor_role, details)
    values ('product_sold', 'transaction', p_transaction_id::text, v_user_id, v_role,
      jsonb_build_object('business_date', v_day, 'total', v_total));
  return p_transaction_id;
end;
$$;

revoke all on function public.process_sale(uuid, text, numeric, numeric, jsonb, timestamptz) from public;
grant execute on function public.process_sale(uuid, text, numeric, numeric, jsonb, timestamptz) to authenticated;

create or replace function public.void_sale(p_transaction_id uuid, p_reason text)
returns void language plpgsql security definer set search_path = public as $$
declare v_role text := get_app_role(); v_tx transactions%rowtype; v_move record;
begin
  if v_role not in ('admin', 'cashier') then raise exception 'Not authorized'; end if;
  if nullif(trim(p_reason), '') is null then raise exception 'Void reason is required'; end if;
  select * into v_tx from transactions where id = p_transaction_id for update;
  if v_tx.id is null then raise exception 'Transaction not found'; end if;
  if v_tx.status = 'voided' then raise exception 'Transaction already voided'; end if;
  if v_role <> 'admin' and v_tx.user_id <> auth.uid() then raise exception 'Not authorized to void this transaction'; end if;
  for v_move in select ingredient_id, quantity from ingredient_movements
    where transaction_id = p_transaction_id and movement_type = 'sale' order by ingredient_id
  loop
    update ingredient_inventory set quantity = quantity + v_move.quantity,
      updated_at = now() where ingredient_id = v_move.ingredient_id;
    insert into ingredient_movements(ingredient_id, movement_type, quantity,
      transaction_id, actor_id, note)
    values (v_move.ingredient_id, 'void', v_move.quantity, p_transaction_id,
      auth.uid(), 'Reversal of completed sale');
  end loop;
  update transactions set status = 'voided', void_reason = trim(p_reason),
    voided_by = auth.uid(), voided_at = now() where id = p_transaction_id;
  insert into audit_log(event_type, entity_type, entity_id, actor_id, actor_role, details)
    values ('product_sale_voided', 'transaction', p_transaction_id::text,
      auth.uid(), v_role, jsonb_build_object('reason', trim(p_reason), 'amount', v_tx.total_amount));
end;
$$;

revoke all on function public.void_sale(uuid, text) from public;
grant execute on function public.void_sale(uuid, text) to authenticated;

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values ('stock-in-evidence', 'stock-in-evidence', false, 5242880,
  array['image/jpeg', 'image/png', 'image/webp', 'application/pdf'])
on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "stock_evidence_admin_read" on storage.objects for select to authenticated
  using (bucket_id = 'stock-in-evidence' and get_app_role() = 'admin');
create policy "stock_evidence_admin_insert" on storage.objects for insert to authenticated
  with check (bucket_id = 'stock-in-evidence' and get_app_role() = 'admin');
create policy "stock_evidence_admin_delete" on storage.objects for delete to authenticated
  using (bucket_id = 'stock-in-evidence' and get_app_role() = 'admin');
